config/routes.rb
Rails.application.routes.draw do
  resources :places
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "places#show"
  
  # config/routes.rb
  get '/places/:id/love', to: 'places#love', as: 'love_place'
  get '/places/:id/hate', to: 'places#hate', as: 'hate_place'


end

app/models/place.rb
class Place < ApplicationRecord
	validates :business_id, presence: true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # before_action :set_place, only: %i[ show edit update destroy ]
  before_action :set_globals

  # GET /places or /places.json
  def index
    liked_places = []
    @likes.each do |like_id|
      liked_places << Place.find(like_id)
    end

    @places = MergeSort.merge_sort_by_user_votes(liked_places)

  end

  # GET /places/1 or /places/1.json
  def show
    @place = @places[@position]
    @image = get_image_path
  end

  def love
    @place = Place.find(params[:id])
    @count = @places.count

    user_votes = @place.user_votes + 1
    @place.update_attribute(:user_votes, user_votes)

    @position += 1
    @likes << @place.id

    session[:position] = @position
    session[:likes] = @likes


    redirect_to place_path(@place)
  end

  def hate
    @place = Place.find(params[:id])

    user_votes = @place.user_votes - 1
    @place.update_attribute(:user_votes, user_votes)

    @position += 1
    session[:position] = @position

    redirect_to place_path(@place)
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:name)
    end

    def get_image_path
      images = Dir.glob("app/assets/images/*.jpg")
      image_path = images.sample
      return image_path.sub("app/assets/images/", "")
    end

    def set_globals
      @places ||= BucketSort.call_sort(Place.where(state: current_user.state).first(150))
      @position ||= session[:position] || 0
      @likes ||= session[:likes] || []
    end

end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <h1>Places</h1>


  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
      </tr>
    </thead>

    <tbody>
      <% @places.each do |place| %>
        <tr>
          <td class="mr-3"><%= place["name"] %></td>
          <td class="ml-3"><%= place["address"] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

  <div class="bg-white p-7 content-center mx-36 text-darkGreen pt-5">
      <!-- content-center w-96 mx-32 mt-10 h-auto p-6 rounded-lg -->
      <div class="">

          <h2 class="text-4xl"><%= @place.name %></h2>
          <%= image_tag @image, class: "rounded-lg"%>
          <!-- <img class="rounded-lg" src="{{ url_for('static', filename='images/starbucks1.jpg') }}" id="featureImage">  -->
          <!-- make it change images -->

          <h3 class="text-xs red_text"><%= @place.address %></h3>

      </div>

      <br>


  </div>

  <div class="p-3">
    <%= @count %>
    <%= link_to 'Hate', hate_place_path(@place), class: "btn bg-danger text-white"%>
    <%= link_to 'Love', love_place_path(@place), class: "btn bg-success text-white"%> 
    <%= link_to 'See Likes', places_path, class: "btn bg-success text-white"%> 
      
      
  </div>

</div>